# Generated by Django 4.1.1 on 2022-10-07 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Landing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                ("detail", models.TextField(verbose_name="detail")),
                ("likes", models.IntegerField(verbose_name="likes")),
                ("hates", models.IntegerField(verbose_name="hates")),
                (
                    "image",
                    models.ImageField(upload_to="landings", verbose_name="image"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Opinion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                ("detail", models.TextField(verbose_name="detail")),
                (
                    "mobile_number",
                    models.CharField(max_length=20, verbose_name="mobile_number"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "mobile_number",
                    models.CharField(max_length=50, verbose_name="mobile_number"),
                ),
                (
                    "landing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landings.landing",
                        verbose_name="reservation",
                    ),
                ),
            ],
        ),
    ]
