# Generated by Django 4.1.1 on 2022-10-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landings", "0002_alter_landing_hates_alter_landing_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landing",
            name="hates",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="hates"
            ),
        ),
        migrations.AlterField(
            model_name="landing",
            name="likes",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="likes"
            ),
        ),
    ]
