# Generated by Django 4.1.1 on 2022-10-07 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("landings", "0004_alter_landing_hates_alter_landing_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landing",
            name="hates",
        ),
        migrations.RemoveField(
            model_name="landing",
            name="likes",
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField(verbose_name="")),
                (
                    "landing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landings.landing",
                        verbose_name="like",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField(verbose_name="")),
                (
                    "landing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landings.landing",
                        verbose_name="",
                    ),
                ),
            ],
        ),
    ]
